default_language_version:
    python: python3.8
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-docstring-first
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-merge-conflict
    -   id: check-vcs-permalinks
    -   id: check-yaml
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: pretty-format-json
        args: ['--autofix']
    -   id: trailing-whitespace
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.5
    hooks:
    -   id: reorder-python-imports
-   repo: https://github.com/ambv/black
    rev: 20.8b1
    hooks:
    -   id: black
        language_version: python3
        require_serial: true # https://github.com/ambv/black/issues/673
